# Generated by Django 5.2.8 on 2025-11-19 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_tbl_place_tbl_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_subcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_category'),
        ),
        migrations.AlterField(
            model_name='tbl_subcategory',
            name='subcategory_name',
            field=models.CharField(max_length=50),
        ),
    ]
