# Generated by Django 5.2.8 on 2025-11-20 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_subcategory_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_place',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_district'),
        ),
    ]
