# Generated by Django 5.2.8 on 2025-11-29 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_course'),
        ('Guest', '0005_remove_tbl_user_place_delete_tbl_college_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_academicyear',
        ),
        migrations.RemoveField(
            model_name='tbl_course',
            name='department',
        ),
        migrations.RemoveField(
            model_name='tbl_place',
            name='district',
        ),
        migrations.DeleteModel(
            name='tbl_semester',
        ),
        migrations.RemoveField(
            model_name='tbl_subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='tbl_course',
        ),
        migrations.DeleteModel(
            name='tbl_department',
        ),
        migrations.DeleteModel(
            name='tbl_place',
        ),
        migrations.DeleteModel(
            name='tbl_subcategory',
        ),
    ]
