# Generated by Django 5.2.8 on 2026-01-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_tbl_academicyear_tbl_department_tbl_semester_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_description', models.CharField(max_length=1400)),
                ('news_file', models.FileField(null=True, upload_to='Assets/AdminDocs/news/file')),
                ('news_photo', models.FileField(null=True, upload_to='Assets/AdminDocs/news/photo')),
                ('news_status', models.IntegerField(default=0)),
            ],
        ),
    ]
