# Generated by Django 5.2.8 on 2025-12-19 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_notes',
        ),
    ]
