# Generated by Django 5.2.8 on 2025-12-30 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0012_tbl_academicyear_tbl_department_tbl_semester_and_more'),
        ('College', '0019_tbl_assignsubject'),
        ('Faculty', '0002_delete_tbl_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_description', models.CharField(max_length=400)),
                ('notes_file', models.FileField(upload_to='Assets/FacultyDocs/Notes/')),
                ('notes_status', models.IntegerField(default=0)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='College.tbl_faculty')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_subject')),
            ],
        ),
    ]
