# Generated by Django 5.2.8 on 2026-01-09 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0019_tbl_assignsubject'),
        ('Faculty', '0003_initial'),
        ('Guest', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_description', models.CharField(max_length=400)),
                ('post_photo', models.FileField(upload_to='Assets/FacultyDocs/Posts/')),
                ('post_status', models.IntegerField(default=0)),
                ('post_pd', models.DateField(auto_now_add=True)),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_college')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='College.tbl_faculty')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='College.tbl_student')),
            ],
        ),
    ]
