# Generated by Django 5.2.8 on 2026-01-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0004_tbl_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_post',
            name='post_type',
            field=models.IntegerField(default=0),
        ),
    ]
