# Generated by Django 5.2.8 on 2026-01-09 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0019_tbl_assignsubject'),
        ('Faculty', '0005_tbl_post_post_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='College.tbl_faculty')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Faculty.tbl_post')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='College.tbl_student')),
            ],
        ),
    ]
