# Generated by Django 5.2.8 on 2026-01-09 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0006_tbl_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_like',
        ),
    ]
