# Generated by Django 5.2.8 on 2026-01-10 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0019_tbl_assignsubject'),
        ('Faculty', '0009_tbl_comment'),
        ('Guest', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_commentreply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentreply_content', models.CharField(max_length=500)),
                ('commentreply_date', models.DateField(auto_now_add=True)),
                ('commentreply_status', models.IntegerField(default=0)),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_college')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Faculty.tbl_comment')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='College.tbl_faculty')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='College.tbl_student')),
            ],
        ),
    ]
