# Generated by Django 5.2.8 on 2026-01-10 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0010_tbl_commentreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_commentreply',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Faculty.tbl_comment'),
        ),
    ]
