# Generated by Django 5.2.8 on 2026-01-10 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0019_tbl_assignsubject'),
        ('Faculty', '0011_alter_tbl_commentreply_comment'),
        ('Guest', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_status', models.IntegerField(default=0)),
                ('follow_date', models.DateField(auto_now_add=True)),
                ('fromcollege_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_college', to='Guest.tbl_college')),
                ('fromfaculty_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_faculty', to='College.tbl_faculty')),
                ('fromstudent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_student', to='College.tbl_student')),
                ('tocollege_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_college', to='Guest.tbl_college')),
                ('tofaculty_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_student', to='College.tbl_faculty')),
                ('tostudent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_student', to='College.tbl_student')),
            ],
        ),
    ]
