# Generated by Django 5.2.8 on 2026-01-10 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0012_tbl_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_follow',
        ),
    ]
