# Generated by Django 5.2.8 on 2025-12-06 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_faculty',
        ),
    ]
