# Generated by Django 5.2.8 on 2025-12-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_collegedepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(max_length=100)),
                ('college_id', models.CharField(max_length=100)),
            ],
        ),
    ]
