# Generated by Django 5.2.8 on 2025-12-12 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0004_tbl_collegedepartment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_collegedepartment',
            old_name='college_id',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='tbl_collegedepartment',
            old_name='department_id',
            new_name='department',
        ),
    ]
