# Generated by Django 5.2.8 on 2025-12-12 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_tbl_academicyear_tbl_department_tbl_semester_and_more'),
        ('College', '0005_rename_college_id_tbl_collegedepartment_college_and_more'),
        ('Guest', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_collegedepartment',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_college'),
        ),
        migrations.AlterField(
            model_name='tbl_collegedepartment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_department'),
        ),
    ]
