# Generated by Django 5.2.8 on 2025-12-12 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0006_alter_tbl_collegedepartment_college_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_collegedepartment',
        ),
    ]
