# Generated by Django 5.2.8 on 2025-12-12 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0008_tbl_collegedepartment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_collegedepartment',
        ),
    ]
