# Generated by Django 5.2.8 on 2025-12-12 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_tbl_academicyear_tbl_department_tbl_semester_and_more'),
        ('College', '0010_tbl_collegedepartment'),
        ('Guest', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_collegecourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_college')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_course')),
            ],
        ),
    ]
