# Generated by Django 5.2.8 on 2025-12-18 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0012_tbl_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_student',
        ),
    ]
