# Generated by Django 5.2.8 on 2025-12-19 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_tbl_academicyear_tbl_department_tbl_semester_and_more'),
        ('College', '0015_delete_tbl_student'),
        ('Guest', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_email', models.CharField(max_length=100)),
                ('student_contact', models.CharField(max_length=100)),
                ('student_bio', models.CharField(max_length=300)),
                ('student_username', models.CharField(max_length=100)),
                ('student_status', models.IntegerField(default=0)),
                ('student_accounttype', models.IntegerField(default=0)),
                ('student_password', models.CharField(max_length=100)),
                ('student_photo', models.FileField(upload_to='Assets/StudentDocs/')),
                ('academicyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_academicyear')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_college')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='College.tbl_collegecourse')),
            ],
        ),
    ]
