# Generated by Django 5.2.8 on 2025-12-19 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0016_tbl_student'),
        ('Faculty', '0002_delete_tbl_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_faculty',
        ),
    ]
