# Generated by Django 5.2.8 on 2025-12-19 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0017_delete_tbl_faculty'),
        ('Guest', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=100)),
                ('faculty_email', models.CharField(max_length=100)),
                ('faculty_contact', models.CharField(max_length=100)),
                ('faculty_photo', models.FileField(upload_to='Assets/CollegeDocs/Faculty/Photo/')),
                ('faculty_password', models.CharField(max_length=100)),
                ('faculty_status', models.IntegerField(default=0)),
                ('faculty_accounttype', models.IntegerField(default=0)),
                ('faculty_doj', models.DateField(auto_now_add=True)),
                ('faculty_bio', models.CharField(max_length=500)),
                ('faculty_username', models.CharField(max_length=50)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_college')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='College.tbl_collegedepartment')),
            ],
        ),
    ]
