# Generated by Django 5.2.8 on 2025-12-19 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_tbl_academicyear_tbl_department_tbl_semester_and_more'),
        ('College', '0018_tbl_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_assignsubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='College.tbl_faculty')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_subject')),
            ],
        ),
    ]
