from django.urls import path,include
from Student import views
app_name="Student"

urlpatterns = [
  path('HomePage/',views.HomePage,name="HomePage"), 
  path('MyProfile/',views.MyProfile,name="MyProfile"),
  path("EditProfile/",views.EditProfile,name="EditProfile"),
  path('topublic/<int:pid>',views.topublic,name="topublic"),
  path('toprivate/<int:prid>',views.toprivate,name="toprivate"),
  path("ChangePassword/",views.ChangePassword,name="ChangePassword"), 
  path("ViewNotes/",views.ViewNotes,name="ViewNotes"),
  path("AjaxCourse/",views.AjaxCourse,name="AjaxCourse"),
  path('Post/',views.Post,name="Post"),
  path('delpost/<int:did>',views.delpost,name="delpost"),
  path('ViewPost/',views.ViewPost,name="ViewPost"), 
  path('likepost/',views.likepost,name="likepost"),
  path('Comment/<int:cid>',views.Comment,name="Comment"), 
  path('ViewCollege/',views.ViewCollege,name="ViewCollege"),
  path('ViewFaculty/',views.ViewFaculty,name="ViewFaculty"),
  path('Follow/<int:cid>',views.Follow,name="Follow"),
  path('FollowF/<int:Fid>',views.FollowF,name="FollowF"),
  path('FollowU/<int:uid>',views.FollowU,name="FollowU"),
  path('StudentList/',views.StudentList,name="StudentList"),
  path('FollowRequest/',views.FollowRequest,name="FollowRequest"),
  path('Followers/',views.Followers,name="Followers"),
  path('ViewCollegeProfile/<int:pid>',views.ViewCollegeProfile,name="ViewCollegeProfile"),
  path('acceptrequest/<int:aid>',views.acceptrequest,name="acceptrequest"),
  path('rejectrequest/<int:rid>',views.rejectrequest,name="rejectrequest"),
  path('Complaint/',views.Complaint,name="Complaint"),
  path('deletecomplaint/<int:did>',views.deletecomplaint,name="deletecomplaint"),
  path('ViewFacultyProfile/<int:fid>',views.ViewFacultyProfile,name="ViewFacultyProfile"),
  path('ViewStudentProfile/<int:sid>',views.ViewStudentProfile,name="ViewStudentProfile"),
  path('chatpage/<int:id>',views.chatpage,name="chatpage"),
  path('ajaxchat/',views.ajaxchat,name="ajaxchat"),
  path('ajaxchatview/',views.ajaxchatview,name="ajaxchatview"),
  path('clearchat/',views.clearchat,name="clearchat"),

  path('fchatpage/<int:id>',views.fchatpage,name="fchatpage"),
  path('fajaxchat/',views.fajaxchat,name="fajaxchat"),
  path('fajaxchatview/',views.fajaxchatview,name="fajaxchatview"),
  path('fclearchat/',views.fclearchat,name="fclearchat"),
  
  path('cchatpage/<int:id>',views.cchatpage,name="cchatpage"),
  path('cajaxchat/',views.cajaxchat,name="cajaxchat"),
  path('cajaxchatview/',views.cajaxchatview,name="cajaxchatview"),
  path('cclearchat/',views.cclearchat,name="cclearchat"),
  path('Search/',views.Search,name="Search"),
]