from django.urls import path,include
from Admin import views
app_name="Admin"

urlpatterns = [
  path('AdminRegistration/',views.AdminRegistration,name="AdminRegistration"), 
  path('HomePage/',views.HomePage,name="HomePage"), 
  path('deladmin/<int:did>',views.deladmin,name="deladmin"),
  path('editadmin/<int:eid>',views.editadmin,name="editadmin"),
  path('District/',views.District,name="District"),
  path('deldistrict/<int:id>',views.deldistrict,name="deldistrict"),
  path('editdistrict/<int:eid>',views.editdistrict,name="editdistrict"),
  path('Category/',views.Category,name="Category"),
  path('delcategory/<int:did>',views.delcategory,name="delcategory"),
  path('editcategory/<int:eid>',views.editcategory,name="editcategory"),
  path('Place/',views.Place,name="Place"),
  path('delplace/<int:id>',views.delplace,name="delplace"),
  path('editplace/<int:id>',views.editplace,name="editplace"),
  path('Subcategory/',views.Subcategory,name="Subcategory"),
  path('delsub/<int:id>',views.delsub,name="delsub"),
  path('editsub/<int:id>',views.editsub,name="editsub"),
  path('UserList/',views.UserList,name="UserList"),
  path('CollegeList/',views.CollegeList,name="CollegeList"),
  path('acceptcollege/<int:aid>',views.acceptcollege,name="acceptcollege"),
  path('rejectcollege/<int:rid>',views.rejectcollege,name="rejectcollege"),
  path('Department/',views.Department,name="Department"),
  path('deldepartment/<int:did>',views.deldepartment,name="deldepartment"),
  path('editdepartment/<int:eid>',views.editdepartment,name="editdepartment"),
  path('Semester/',views.Semester,name="Semester"),
  path('delsemester/<int:did>',views.delsemester,name="delsemester"),
  path('editsemester/<int:eid>',views.editsemester,name="editsemester"),
  path('Academicyear/',views.Academicyear,name="Academicyear"),
  path('delacademicyear/<int:did>',views.delacademicyear,name="delacademicyear"),
  path('editacademicyear/<int:eid>',views.editacademicyear,name="editacademicyear"),
  path('Course/',views.Course,name="Course"),
  path('delcourse/<int:did>',views.delcourse,name="delcourse"),
  path('editcourse/<int:eid>',views.editcourse,name="editcourse"),
  path('Subject/',views.Subject,name="Subject"),
  path('delsubject/<int:did>',views.delsubject,name="delsubject"),
  path('editsubject/<int:eid>',views.editsubject,name="editsubject"),
  path('AjaxCourse/',views.AjaxCourse,name="AjaxCourse"),
  path('ViewComplaint/',views.ViewComplaint,name="ViewComplaint"),
  path('Reply/<int:rrid>',views.Reply,name="Reply"),
  path('Addnews/',views.Addnews,name="Addnews"),
  path('delnews/<int:did>',views.delnews,name="delnews"),
]