# Generated by Django 5.2.8 on 2026-01-22 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
