# Generated by Django 5.2.8 on 2026-01-22 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('College', '0019_tbl_assignsubject'),
        ('Faculty', '0014_tbl_follow'),
        ('Guest', '0006_initial'),
        ('Student', '0004_delete_tbl_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=400)),
                ('complaint_content', models.CharField(max_length=1400)),
                ('complaint_reply', models.CharField(max_length=1400, null=True)),
                ('complaint_status', models.IntegerField(default=0)),
                ('complaint_date', models.DateField(auto_now_add=True)),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_college')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='College.tbl_faculty')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Faculty.tbl_post')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='College.tbl_student')),
            ],
        ),
    ]
