# Generated by Django 5.2.8 on 2026-01-22 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0010_tbl_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_chat',
        ),
    ]
