# Generated by Django 5.2.8 on 2026-01-23 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0019_tbl_assignsubject'),
        ('Guest', '0006_initial'),
        ('Student', '0013_delete_tbl_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_content', models.CharField(max_length=500)),
                ('chat_time', models.DateTimeField()),
                ('chat_file', models.FileField(upload_to='ChatFiles/')),
                ('college_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='college_from', to='Guest.tbl_college')),
                ('college_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='college_to', to='Guest.tbl_college')),
                ('faculty_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_from', to='College.tbl_faculty')),
                ('faculty_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_to', to='College.tbl_faculty')),
                ('student_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_from', to='College.tbl_student')),
                ('student_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_to', to='College.tbl_student')),
            ],
        ),
    ]
