# Generated by Django 5.2.8 on 2026-02-19 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0015_tbl_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_rating',
        ),
    ]
