# Generated by Django 5.2.8 on 2026-02-19 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0019_tbl_assignsubject'),
        ('Guest', '0006_initial'),
        ('Student', '0016_delete_tbl_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_data', models.IntegerField()),
                ('user_review', models.CharField(max_length=500)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_college')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='College.tbl_faculty')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='College.tbl_student')),
            ],
        ),
    ]
