# Generated by Django 5.2.8 on 2026-02-19 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0019_tbl_assignsubject'),
        ('Guest', '0006_initial'),
        ('Student', '0017_tbl_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_rating',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_college'),
        ),
        migrations.AlterField(
            model_name='tbl_rating',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='College.tbl_faculty'),
        ),
        migrations.AlterField(
            model_name='tbl_rating',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='College.tbl_student'),
        ),
    ]
