# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0018_alter_tbl_rating_college_alter_tbl_rating_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_chat',
            name='chat_file',
            field=models.FileField(blank=True, null=True, upload_to='ChatFiles/'),
        ),
        migrations.AddField(
            model_name='tbl_chat',
            name='chat_seen',
            field=models.BooleanField(default=False),
        ),
    ]
