from django.urls import path,include
from College import views
app_name="College"

urlpatterns = [
  path('HomePage/',views.HomePage,name="HomePage"),  
  path('CollegeProfile/',views.CollegeProfile,name="CollegeProfile"),
  path("EditProfile/",views.EditProfile,name="EditProfile"),
  path("ChangePassword/",views.ChangePassword,name="ChangePassword"),
  path('FacultyRegistration/',views.FacultyRegistration,name="FacultyRegistration"),
  path('delfaculty/<int:did>',views.delfaculty,name="delfaculty"),
  path('CollegeDepartment/',views.CollegeDepartment,name="CollegeDepartment"),
  path('deldepartment/<int:did>',views.deldepartment,name="deldepartment"),
  path('CollegeCourse/',views.CollegeCourse,name="CollegeCourse"),
  path('delcourse/<int:did>',views.delcourse,name="delcourse"),
  path('AjaxCollegeCourse/',views.AjaxCollegeCourse,name="AjaxCollegeCourse"),
  path('AssignSubject/<int:fid>',views.AssignSubject,name="AssignSubject"),
  path('AjaxSubject/',views.AjaxSubject,name="AjaxSubject"),
  path('delsubject/<int:did>',views.delsubject,name="delsubject"),
  path('Post/',views.Post,name="Post"),
  path('delpost/<int:did>',views.delpost,name="delpost"),
  path('ViewPost/',views.ViewPost,name="ViewPost"),
  path('likepost/',views.likepost,name="likepost"),
  path('Comment/<int:cid>',views.Comment,name="Comment"),
  path('FollowF/<int:fid>',views.FollowF,name="FollowF"),
  path('FollowC/<int:Cid>',views.FollowC,name="FollowC"),
  path('FacultyList/',views.FacultyList,name="FacultyList"),
  path('CollegeList/',views.CollegeList,name="CollegeList"),
  path('StudentList/',views.StudentList,name="StudentList"),
  path('FollowS/<int:Sid>',views.FollowS,name="FollowS"),
  path('Followers/',views.Followers,name="Followers"),
  path('acceptrequest/<int:aid>',views.acceptrequest,name="acceptrequest"),
  path('rejectrequest/<int:rid>',views.rejectrequest,name="rejectrequest"),
  path('Complaint',views.Complaint,name="Complaint"),
  path('deletecomplaint/<int:did>',views.deletecomplaint,name="deletecomplaint"),
  path('ViewCollegeProfile/<int:pid>',views.ViewCollegeProfile,name="ViewCollegeProfile"),
  path('ViewStudentProfile/<int:sid>',views.ViewStudentProfile,name="ViewStudentProfile"),
  path('ViewFacultyProfile/<int:fid>',views.ViewFacultyProfile,name="ViewFacultyProfile"),
  path('chatpage/<int:id>',views.chatpage,name="chatpage"),
  path('ajaxchat/',views.ajaxchat,name="ajaxchat"),
  path('ajaxchatview/',views.ajaxchatview,name="ajaxchatview"),
  path('clearchat/',views.clearchat,name="clearchat"),
  path('schatpage/<int:id>',views.schatpage,name="schatpage"),
  path('sajaxchat/',views.sajaxchat,name="sajaxchat"),
  path('sajaxchatview/',views.sajaxchatview,name="sajaxchatview"),
  path('sclearchat/',views.sclearchat,name="sclearchat"),
  path('fchatpage/<int:id>',views.fchatpage,name="fchatpage"),
  path('fajaxchat/',views.fajaxchat,name="fajaxchat"),
  path('fajaxchatview/',views.fajaxchatview,name="fajaxchatview"),
  path('fclearchat/',views.fclearchat,name="fclearchat"),
  
  
]