# Generated by Django 5.2.8 on 2025-11-27 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_place_district'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_college',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=100)),
                ('college_email', models.CharField(max_length=100)),
                ('college_password', models.CharField(max_length=100)),
                ('college_address', models.CharField(max_length=100)),
                ('college_photo', models.FileField(upload_to='Assets/CollegeDocs/Photo')),
                ('college_logo', models.FileField(upload_to='Assets/CollegeDocs/Logo')),
                ('college_proof', models.FileField(upload_to='Assets/CollegeDocs/Proof')),
                ('college_contact', models.CharField(max_length=100)),
                ('college_status', models.CharField(max_length=100)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
