# Generated by Django 5.2.8 on 2025-11-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_tbl_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_college',
            name='college_logo',
            field=models.FileField(upload_to='Assets/CollegeDocs/Logo/'),
        ),
        migrations.AlterField(
            model_name='tbl_college',
            name='college_photo',
            field=models.FileField(upload_to='Assets/CollegeDocs/Photo/'),
        ),
        migrations.AlterField(
            model_name='tbl_college',
            name='college_proof',
            field=models.FileField(upload_to='Assets/CollegeDocs/Proof/'),
        ),
    ]
