# Generated by Django 5.2.8 on 2025-11-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_alter_tbl_college_college_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_college',
            name='college_status',
            field=models.IntegerField(default=0),
        ),
    ]
