# Generated by Django 5.2.8 on 2025-11-29 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_alter_tbl_college_college_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_user',
            name='place',
        ),
        migrations.DeleteModel(
            name='tbl_college',
        ),
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
