# Generated by Django 5.2.8 on 2025-11-29 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0012_tbl_academicyear_tbl_department_tbl_semester_and_more'),
        ('Guest', '0005_remove_tbl_user_place_delete_tbl_college_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_college',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=100)),
                ('college_email', models.CharField(max_length=100)),
                ('college_password', models.CharField(max_length=100)),
                ('college_address', models.CharField(max_length=100)),
                ('college_photo', models.FileField(upload_to='Assets/CollegeDocs/Photo/')),
                ('college_logo', models.FileField(upload_to='Assets/CollegeDocs/Logo/')),
                ('college_proof', models.FileField(upload_to='Assets/CollegeDocs/Proof/')),
                ('college_contact', models.CharField(max_length=100)),
                ('college_status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_contact', models.CharField(max_length=50)),
                ('user_address', models.CharField(max_length=80)),
                ('user_password', models.CharField(max_length=50)),
                ('user_photo', models.FileField(upload_to='Assets/UserDocs/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
